codecov:
  require_ci_to_pass: yes

# Help Codecov find source files when using Kotlin's short package syntax
#fixes:
#  - "::/"                                 # Root level fix
#  - "com.the13haven.kotfild.ksp/::"       # If this is your package prefix
#  - "com.the13haven.kotfild/::"           # Another common package prefix
#  - "::ksp/src/main/kotlin/"              # Map source directories
#  - "::lib/src/main/kotlin/"              # For the lib module

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 80%
        threshold: 2%
      ksp:
        flags:
          - ksp
      lib:
        flags:
          - lib

flags:
  ksp:
    paths:
      - ksp/
    carryforward: true
  lib:
    paths:
      - lib/
    carryforward: true

parsers:
  jacoco:
    partials_as_hits: yes
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
