name: Kotfild CI Build

on:
  workflow_dispatch:

  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

permissions:
  actions: read
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Run build with Gradle Wrapper
        run: ./gradlew build --no-daemon

      - name: Upload KSP module coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./build/coverage-reports/ksp.xml
          flags: ksp
          fail_ci_if_error: true

      - name: Upload Lib module coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./build/coverage-reports/lib.xml
          flags: lib
          fail_ci_if_error: true

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        # if: ${{ github.ref_name == 'main' }}
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: the13haven/kotfild
#          directory: ./build/coverage-reports
#          fail_ci_if_error: true
#          verbose: true

#      - name: Upload ksp test reports to Codecov
#        uses: codecov/test-results-action@v1
#        # if: ${{ github.ref_name == 'main' }}
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: the13haven/kotfild
#          flags: ksp
#          directory: ksp/build/test-results/test
#          fail_ci_if_error: true
#
#      - name: Upload lib test reports to Codecov
#        uses: codecov/test-results-action@v1
#        # if: ${{ github.ref_name == 'main' }}
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: the13haven/kotfild
#          flags: lib
#          directory: lib/build/test-results/test
#          fail_ci_if_error: true

  fossa-scan:

    if: ${{ github.ref_name == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: FOSSA Scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          project: kotfild

      - name: FOSSA Test
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          project: kotfild
          run-tests: true
